CREATE TABLE KH_STUDENT(
	STD_NO     NUMBER PRIMARY KEY,
	STD_NAME     NVARCHAR2(5) NOT NULL,
	STD_AGE     NUMBER NOT NULL,
	MAJOR   NVARCHAR2(10) NOT NULL,
	ENT_DATE DATE DEFAULT SYSDATE
);

COMMENT ON COLUMN KH_STUDENT.STD_NO   IS '학생 번호';
COMMENT ON COLUMN KH_STUDENT.STD_NAME IS '학생 이름';
COMMENT ON COLUMN KH_STUDENT.STD_AGE  IS '학생 나이';
COMMENT ON COLUMN KH_STUDENT.MAJOR    IS '학생 전공';
COMMENT ON COLUMN KH_STUDENT.ENT_DATE IS '입학날짜';


CREATE SEQUENCE SEQ_STD_NO NOCACHE;

COMMIT;

SELECT * FROM KH_STUDENT;

			

